[tool.poetry]
name = "valentBind"
version = "0.1.0"
description = ""
authors = ["Aaron Meyer <ameyer@ucla.edu>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
numpy = "^1.20.3"
scipy = "^1.7.0"
mypy = "^0.910"
jax = "^0.2.25"
jaxlib = "^0.1.74"
jaxopt = "^0.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
