[tool.poetry]
name = "valentBind"
version = "0.1.0"
description = ""
authors = ["Aaron Meyer <ameyer@ucla.edu>"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.20.3"
jax = "^0.2.13"
jaxlib = "^0.1.67"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
