[tool.poetry]
name = "valentBind"
version = "0.1.0"
description = "The multivalent binding model implemented in Python."
authors = ["Aaron Meyer <ameyer@ucla.edu>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
numpy = "^1.20"
scipy = "^1.8"
jax = ">=0.2.25"
jaxlib = ">=0.3.0"
jaxopt = ">=0.3.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
mypy = "^0.910"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
