name: Code Quality

on: [push]

jobs:
  code-quality:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true
          version: '0.39.0'

      - name: Formatting
        run: rye fmt --check

      - name: Linting
        run: rye lint

      - name: Static type checks (pyright)
        run: make pyright