name: Test

on: [push]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: false
      - name: Run tests
        run: make test
